version: 1.0.0

display:
  width: 3440
  height: 1440
  frame_rate: 60

grid:
  cell_size: 100
  x_size: 10
  y_size: 10
  show_trajectories: true
  show_grid: true

agents:
  num_agents: 1000
  road_user_taxonomy:
    - type: pedestrian
      proportion: 0.5
      radius: 5.0
      color: 'blue'
      min_velocity: 1
      max_velocity: 2
    - type: cyclist
      proportion: 0.1
      radius: 5.0
      color: 'green'
      min_velocity: 2
      max_velocity: 4
    - type: e-scooter
      proportion: 0.2
      radius: 5.0
      color: 'red'
      min_velocity: 3
      max_velocity: 5
    - type: senior
      proportion: 0.1
      radius: 5.0
      color: 'purple'
      min_velocity: 0.5
      max_velocity: 1
    - type: child
      proportion: 0.1
      radius: 5.0
      color: 'orange'
      min_velocity: 1
      max_velocity: 2

simulation:
  duration_seconds: 3
  maximum_frames: 1000
  # scenario: random