version: 1.0.0

display:
  width: 3440
  height: 1440
  pixels_per_meter: 20

grid:
  cell_size: 100
  show_trajectories: true
  show_grid: true
  show_info: true

agents:
  num_agents: 50
  grouping:
    families:
      allow: false
      size: 3
      probability: 0.1
    general:
      allow: false
      size: 2
      probability: 0.1
  road_user_taxonomy:
    - type: Child Pedestrian
      probability: 0.1
      priority: 1
      radius: 0.2
      color: 'indigo'
      velocity:
        min: 0.8    # 2.9 km/h  
        max: 1.667  # 6 km/h
      acceleration:
        min: 0.5
        max: 1.5
    - type: Senior Pedestrian
      probability: 0.1
      priority: 2
      radius: 0.225
      color: 'purple'
      velocity:
        min: 0.8  # 2.9 km/h  
        max: 1.5  # 5.4 km/h
      acceleration:
        min: 0.5
        max: 1.2
    - type: Adult Pedestrian
      probability: 0.4
      priority: 3
      radius: 0.25
      color: 'blue'
      velocity:
        min: 1      # 3.6 km/h
        max: 1.667  # 6 km/h
      acceleration:
        min: 0.68
        max: 1.44
    - type: Senior Cyclist
      probability: 0.1
      priority: 4
      radius: 1.0
      color: 'orange'
      velocity:
        min: 2.5  # 9 km/h
        max: 5.5  # 20 km/h
      acceleration:
        min: 0.5
        max: 1.5
    - type: Adult Cyclist
      probability: 0.1
      priority: 5
      radius: 1.0
      color: 'green'
      velocity:
        min: 3.6  # 13 km/h
        max: 10   # 36 km/h
      acceleration:
        min: 1.5
        max: 4.0
    - type: Adult E-Scooter Driver
      probability: 0.2
      priority: 6
      radius: 0.65
      color: 'red'
      velocity:
        min: 5     # 18 km/h
        max: 6.11  # 22 km/h
      acceleration:
        min: 2.0
        max: 4.5
   
simulation:
  duration_seconds: 100
  maximum_frames: 50
  time_step: 0.02
  scenario: random # not used

common:
  debug: false # not used
  log_level: info # not used
  headless: false # not used

database:
  host: localhost
  port: 27017
  db_name: Simulation
  collection_name: Agents
  db_directory: /User/${whoami}/data/db # mongod --dbpath /User/${whoami}/data/db

  # TODO: include buffer radius, buffer offset

obstacles:
  - type: rectangle
    position: [10.0, 10.0]  # Position in meters
    size: [10, 5.0]      # Size in meters
    color: grey