objects:
  - name: cube1
    position: [0.0, 2.5, -5.0]
    dimensions: [2.0, 5.0, 1.0]
    color: [1.0, 0.0, 0.0]  # Red

  - name: cube2
    position: [2.0, 0.75, -8.0]
    dimensions: [0.5, 1.5, 2.5]
    color: [0.5, 0.0, 0.5]  # Purple

  - name: cube3
    position: [-4.0, 1.5, -8.0]
    dimensions: [2.5, 3.0, 2.5]
    color: [0.0, 1.0, 0.0]  # Purple

  - name: cube4
    position: [4.0, 1.5, -4.5]
    dimensions: [1.5, 3.0, 1.5]
    color: [0.5, 1.0, 0.5]  # Purple
