display:
  width: 3440
  height: 1440
  pixels_per_meter: 20
  title: 'Agent-Based Urban Mobility Simulator'
  show_info: true

simulation:
  # duration_seconds: 10
  maximum_frames: 10
  time_step: 0.05
  playback_speed: 1.0
  num_threads: 8
  live_mode: true
  show_grid: true

agents:
  num_agents: 100
  waypoint_distance: 100.0
  show_trajectories: false
  show_waypoints: false