version: 1.0

display:
  width: 2400 # 2680
  height: 1200 # 1680
  pixels_per_meter: 20
  title: 'Urban Mobility Simulator'

renderer:
  show_renderer: true
  show_obstacles: false
  show_corridors: false
  show_trajectories: false
  show_waypoints: false
  show_arrow: true
  show_buffer: true
  show_info: true
  show_grids: true
  show_sensors: false

simulation:
  width: 120
  height: 60
  duration_seconds: 10
  maximum_frames: 10
  time_step: 0.05
  playback_speed: 1.0
  num_threads: 8
  # scenario: random # not used
  datetime: '2024-08-22T08:30:00'
  make_video: false

collision:
  grid:
    cell_size: 20 # Default: 100
    show_grid: true

agents:
  num_agents: 50
  waypoint_distance: 20
  waypoint_radius: 2
  grouping:
    families:
      allow: false
      size: 3
      probability: 0.1
    general:
      allow: false
      size: 2
      probability: 0.1
  road_user_taxonomy:
    - type: Child Pedestrian
      probability: 0.1
      priority: 1
      radius: 0.2
      color: 'magenta'
      velocity:
        min: 0.8    # 2.9 km/h  
        max: 1.667  # 6 km/h
        mu: 1.0     # 3.6 km/h
        sigma: 0.2
        noise_scale: 0.05
        noise_factor: 0.5
      acceleration:
        min: 0.5
        max: 1.5
      look_ahead_time: 2.0 # Part of behavior profile (foresightfulness)
    - type: Senior Pedestrian
      probability: 0.1
      priority: 2
      radius: 0.225
      color: 'purple'
      velocity:
        min: 0.8  # 2.9 km/h  
        max: 1.5  # 5.4 km/h
        mu: 0.9   # 3.2 km/h
        sigma: 0.2
        noise_scale: 0.05
        noise_factor: 0.5
      acceleration:
        min: 0.5
        max: 1.2
      look_ahead_time: 2.0 # Part of behavior profile (foresightfulness)
    - type: Adult Pedestrian
      probability: 0.4
      priority: 3
      radius: 0.25
      color: 'blue'
      velocity:
        min: 1      # 3.6 km/h
        max: 1.667  # 6 km/h
        mu: 1.4     # 5 km/h
        sigma: 0.2
        noise_scale: 0.05
        noise_factor: 0.5
      acceleration:
        min: 0.68
        max: 1.44
      look_ahead_time: 2.0 # Part of behavior profile (foresightfulness)
    - type: Senior Cyclist
      probability: 0.1
      priority: 4
      radius: 1.0
      color: 'orange'
      velocity:
        min: 2.5  # 9 km/h
        max: 5.5  # 20 km/h
        mu: 4.0   # 14.4 km/h
        sigma: 0.2
        noise_scale: 0.05
        noise_factor: 0.5
      acceleration:
        min: 0.5
        max: 1.5
      look_ahead_time: 5.0 # Part of behavior profile (foresightfulness)
    - type: Adult Cyclist
      probability: 0.1
      priority: 5
      radius: 1.0
      color: 'green'
      velocity:
        min: 3.6  # 13 km/h
        max: 10   # 36 km/h
        mu: 6.0 # 21.6 km/h
        sigma: 0.3
        noise_scale: 0.05
        noise_factor: 0.5
      acceleration:
        min: 1.5
        max: 4.0
      look_ahead_time: 5.0 # Part of behavior profile (foresightfulness)
    - type: Adult E-Scooter Driver
      probability: 0.2
      priority: 6
      radius: 0.65
      color: 'red'
      velocity:
        min: 5     # 18 km/h
        max: 6.11  # 22 km/h
        mu: 5.6    # 20 km/h
        sigma: 0.1
        noise_scale: 0.05
        noise_factor: 0.5
      acceleration:
        min: 2.0
        max: 4.5
      look_ahead_time: 5.0 # Part of behavior profile (foresightfulness)

common:
  debug: false # not used
  log_level: info # not used

database:
  host: localhost
  port: 27017
  db_name: Simulation
  collection_name: Agents
  db_directory: /User/${whoami}/data/db # mongod --dbpath /User/${whoami}/data/db
  clear_database: true

sensors:
  - type: agent-based
    frame_rate: 10.0
    color: blue
    alpha: 0.1
    database:
      db_name: Simulation
      collection_name: AB_Sensor_Data
  - type: grid-based
    frame_rate: 10.0
    color: green
    alpha: 0.1
    grid:
      show_grid: true
    database:
      db_name: Simulation
      collection_name: GB_Sensor_Data