version: 1.0

display:
  width: 800 # 2680
  height: 800 # 1680
  pixels_per_meter: 10
  title: 'Urban Mobility Simulator V3'

renderer:
  show_renderer: true
  show_obstacles: false
  show_corridors: false
  show_trajectories: false
  show_waypoints: false
  show_arrow: true
  show_buffer: true
  show_info: true
  show_grids: true
  show_sensors: true

simulation:
  width: 80
  height: 80
  duration_seconds: 100
  maximum_frames: 100
  time_step: 0.05
  playback_speed: 1.0
  num_threads: 8
  # scenario: random # not used
  datetime: '2025-02-03T10:30:00'

collision:
  grid:
    cell_size: 10 # Default: 100
    show_grid: true

# quadtree:
#   grid:
#     cell_size: 500
#     show_grid: true
#     max_depth: 7

agents:
  num_agents: 100
  waypoint_distance: 20
  waypoint_radius: 2
  grouping:
    families:
      allow: false
      size: 3
      probability: 0.1
    general:
      allow: false
      size: 2
      probability: 0.1
  road_user_taxonomy:
    - type: Child Pedestrian
      probability: 0.1
      priority: 1
      radius: 0.2
      color: 'magenta'
      velocity:
        min: 0.8    # 2.9 km/h  
        max: 1.667  # 6 km/h
        mu: 1.0     # 3.6 km/h
        sigma: 0.2
        noise_scale: 0.05
        noise_factor: 0.5
      acceleration:
        min: 0.5
        max: 1.5
      look_ahead_time: 2.0 # Part of behavior profile (foresightfulness)
    - type: Senior Pedestrian
      probability: 0.1
      priority: 2
      radius: 0.225
      color: 'purple'
      velocity:
        min: 0.8  # 2.9 km/h  
        max: 1.5  # 5.4 km/h
        mu: 0.9   # 3.2 km/h
        sigma: 0.2
        noise_scale: 0.05
        noise_factor: 0.5
      acceleration:
        min: 0.5
        max: 1.2
      look_ahead_time: 2.0 # Part of behavior profile (foresightfulness)
    - type: Adult Pedestrian
      probability: 0.4
      priority: 3
      radius: 0.25
      color: 'blue'
      velocity:
        min: 1      # 3.6 km/h
        max: 1.667  # 6 km/h
        mu: 1.4     # 5 km/h
        sigma: 0.2
        noise_scale: 0.05
        noise_factor: 0.5
      acceleration:
        min: 0.68
        max: 1.44
      look_ahead_time: 2.0 # Part of behavior profile (foresightfulness)
    - type: Senior Cyclist
      probability: 0.1
      priority: 4
      radius: 1.0
      color: 'orange'
      velocity:
        min: 2.5  # 9 km/h
        max: 5.5  # 20 km/h
        mu: 4.0   # 14.4 km/h
        sigma: 0.2
        noise_scale: 0.05
        noise_factor: 0.5
      acceleration:
        min: 0.5
        max: 1.5
      look_ahead_time: 5.0 # Part of behavior profile (foresightfulness)
    - type: Adult Cyclist
      probability: 0.1
      priority: 5
      radius: 1.0
      color: 'green'
      velocity:
        min: 3.6  # 13 km/h
        max: 10   # 36 km/h
        mu: 6.0 # 21.6 km/h
        sigma: 0.3
        noise_scale: 0.05
        noise_factor: 0.5
      acceleration:
        min: 1.5
        max: 4.0
      look_ahead_time: 5.0 # Part of behavior profile (foresightfulness)
    - type: Adult E-Scooter Driver
      probability: 0.2
      priority: 6
      radius: 0.65
      color: 'red'
      velocity:
        min: 5     # 18 km/h
        max: 6.11  # 22 km/h
        mu: 5.6    # 20 km/h
        sigma: 0.1
        noise_scale: 0.05
        noise_factor: 0.5
      acceleration:
        min: 2.0
        max: 4.5
      look_ahead_time: 5.0 # Part of behavior profile (foresightfulness)

common:
  debug: false # not used
  log_level: info # not used

database:
  host: localhost
  port: 27017
  db_name: Simulation
  collection_name: Agents
  db_directory: /User/${whoami}/data/db # mongod --dbpath /User/${whoami}/data/db
  clear_database: true

sensors:
  # - type: agent-based
  #   frame_rate: 10.0
  #   detection_area:
  #     x: 0.0
  #     y: 0.0
  #     width: 60.0 # default: 115.0
  #     height: 30.0 # 120
  #     color: blue
  #     alpha: 0.1
  #   database:
  #     db_name: Simulation
  #     collection_name: AB_Sensor_Data_V3
  # - type: grid-based
  #   frame_rate: 1.0
  #   detection_area:
  #     x: 0.0
  #     y: 0.0
  #     width: 40.0 # default: 85.0
  #     height: 40.0 # default: 72.0
  #     color: red
  #     alpha: 0.1
  #   grid:
  #     cell_size: 10 # in meters
  #     show_grid: true
  #   database:
  #     db_name: Simulation
  #     collection_name: GB_Sensor_Data_V3
  - type: adaptive-grid-based
    frame_rate: 1.0
    detection_area:
      x: 0.0
      y: 0.0
      width: 40.0 # default: 85.0
      height: 40.0 # default: 72.0
      color: green
      alpha: 0.1
    grid:
      cell_size: 20 # in meters // TO-DO: remove and use max(width, height) / 2
      show_grid: true
      max_depth: 2
    database:
      db_name: Simulation
      collection_name: AGB_Sensor_Data_V3

# obstacles:
#   - type: rectangle
#     position: [0.0, 0.0]  # Position in meters
#     size: [10, 5.0]      # Size in meters
#     color: grey

# corridors:
#   - type: start
#     position: [0.0, 0.0]
#     width: 2.0
#     height: 72.0
#     color: grey
#     alpha: 0.1
#   - type: end
#     position: [170.0, 0.0]
#     width: 2.0
#     height: 72.0
#     color: red
#     alpha: 0.1

location:
  latitude: 53.55703
  longitude: 10.02303
